#!/usr/bin/env python

APPNAME = 'do3se_generic'
VERSION = '1.0'

def options(ctx):
    ctx.load('compiler_c')
    ctx.load('compiler_fc')


def configure(ctx):
    ctx.load('compiler_c')
    ctx.load('compiler_fc')


def build(ctx):
    ctx(features='fc fcprogram',
        source='main.f90',
        target=APPNAME,
        use='do3se')
