# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcframe_mainwindow(wx.Frame):
#!XRCED:begin-block:xrcframe_mainwindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_mainwindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_mainwindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.html_about = xrc.XRCCTRL(self, "html_about")
        self.list_recent = xrc.XRCCTRL(self, "list_recent")
        self.btn_open_selected = xrc.XRCCTRL(self, "btn_open_selected")
        self.btn_open_other = xrc.XRCCTRL(self, "btn_open_other")
        self.btn_new = xrc.XRCCTRL(self, "btn_new")



class xrcframe_projectwindow(wx.Frame):
#!XRCED:begin-block:xrcframe_projectwindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_projectwindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_projectwindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.tb_main = xrc.XRCCTRL(self, "tb_main")
        self.html_introduction = xrc.XRCCTRL(self, "html_introduction")
        self.pnl_errors = xrc.XRCCTRL(self, "pnl_errors")
        self.list_errors = xrc.XRCCTRL(self, "list_errors")
        self.btn_errors = xrc.XRCCTRL(self, "btn_errors")
        self.prg_progress = xrc.XRCCTRL(self, "prg_progress")
        self.btn_run = xrc.XRCCTRL(self, "btn_run")
        self.btn_close = xrc.XRCCTRL(self, "btn_close")

        self.Bind(wx.EVT_CLOSE, self.OnClose)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_errors, self.btn_errors)

#!XRCED:begin-block:xrcframe_projectwindow.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcframe_projectwindow.OnClose        

#!XRCED:begin-block:xrcframe_projectwindow.OnButton_btn_errors
    def OnButton_btn_errors(self, evt):
        # Replace with event handler code
        print "OnButton_btn_errors()"
#!XRCED:end-block:xrcframe_projectwindow.OnButton_btn_errors        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ui_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="frame_mainwindow">
    <title>DO3SE</title>
    
    <object class="wxPanel">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxHtmlWindow" name="html_about">
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxStaticText">
                <label>Recent projects</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxListBox" name="list_recent">
                <style>wxLB_SINGLE</style>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxVERTICAL</orient>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>5</border>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxButton" name="btn_open_selected">
                <label>Open &amp;selected</label>
                <enabled>0</enabled>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_open_other">
                <label>&amp;Open other...</label>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_new">
                <label>&amp;New project</label>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxHORIZONTAL</orient>
          </object>
          <flag>wxBOTTOM|wxLEFT|wxRIGHT|wxALIGN_RIGHT</flag>
          <border>5</border>
        </object>
      </object>
    </object>
  </object>
  <object class="wxFrame" name="frame_projectwindow">
    <object class="wxMenuBar">
      <object class="wxMenu">
        <object class="wxMenuItem">
          <label>New</label>
          <bitmap stock_id="wxART_NEW"/>
        </object>
        <object class="wxMenuItem">
          <label>Open...</label>
          <bitmap stock_id="wxART_FILE_OPEN"/>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem">
          <label>Save</label>
          <bitmap stock_id="wxART_FILE_SAVE"/>
        </object>
        <object class="wxMenuItem">
          <label>Save as...</label>
          <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        </object>
        <object class="wxMenuItem">
          <label>Close</label>
          <bitmap stock_id="wxART_CROSS_MARK"/>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem">
          <label>Close all</label>
          <bitmap stock_id="wxART_QUIT"/>
        </object>
        <label>&amp;Project</label>
      </object>
      <object class="wxMenu">
        <label>&amp;Tools</label>
      </object>
    </object>
    
    <title>DO3SE (foo.do3se)</title>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
    <object class="wxPanel">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxTreebook" name="tb_main">
            <object class="treebookpage">
              <object class="wxPanel">
                <object class="wxBoxSizer">
                  <orient>wxVERTICAL</orient>
                  <object class="sizeritem">
                    <object class="wxHtmlWindow" name="html_introduction">
                      <htmlcode>&lt;p&gt;
This is the main project window.  Each of the items on the left refer to a group of model parameters/settings which can be changed.
&lt;/p&gt;</htmlcode>
                      <style>wxNO_BORDER</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                </object>
              </object>
              <label>Introduction</label>
              <depth>0</depth>
            </object>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxPanel" name="pnl_errors">
            <object class="wxBoxSizer">
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Errors</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxListBox" name="list_errors">
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
            </object>
            <hidden>1</hidden>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
          <border>5</border>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxButton" name="btn_errors">
                <label>121 errors (click for more information)</label>
                <fg>#FF1111</fg>
                <style>wxNO_BORDER|wxNO_BORDER</style>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxGauge" name="prg_progress">
                <range>100</range>
                <value>50</value>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_run">
                <label>Run</label>
                <enabled>0</enabled>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_close">
                <label>Close</label>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxHORIZONTAL</orient>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>5</border>
        </object>
      </object>
    </object>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ui/ui_xrc', ui_xrc)
    __res.Load('memory:XRC/ui/ui_xrc')

