# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcframe_mainwindow(wx.Frame):
#!XRCED:begin-block:xrcframe_mainwindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_mainwindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_mainwindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.html_about = xrc.XRCCTRL(self, "html_about")
        self.list_recent = xrc.XRCCTRL(self, "list_recent")
        self.btn_open_selected = xrc.XRCCTRL(self, "btn_open_selected")
        self.btn_open_other = xrc.XRCCTRL(self, "btn_open_other")
        self.btn_new = xrc.XRCCTRL(self, "btn_new")

        self.Bind(wx.EVT_LISTBOX, self.OnListbox_list_recent, self.list_recent)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnListbox_dclick_list_recent, self.list_recent)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_open_selected, self.btn_open_selected)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_open_other, self.btn_open_other)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_new, self.btn_new)

#!XRCED:begin-block:xrcframe_mainwindow.OnListbox_list_recent
    def OnListbox_list_recent(self, evt):
        # Replace with event handler code
        print "OnListbox_list_recent()"
#!XRCED:end-block:xrcframe_mainwindow.OnListbox_list_recent        

#!XRCED:begin-block:xrcframe_mainwindow.OnListbox_dclick_list_recent
    def OnListbox_dclick_list_recent(self, evt):
        # Replace with event handler code
        print "OnListbox_dclick_list_recent()"
#!XRCED:end-block:xrcframe_mainwindow.OnListbox_dclick_list_recent        

#!XRCED:begin-block:xrcframe_mainwindow.OnButton_btn_open_selected
    def OnButton_btn_open_selected(self, evt):
        # Replace with event handler code
        print "OnButton_btn_open_selected()"
#!XRCED:end-block:xrcframe_mainwindow.OnButton_btn_open_selected        

#!XRCED:begin-block:xrcframe_mainwindow.OnButton_btn_open_other
    def OnButton_btn_open_other(self, evt):
        # Replace with event handler code
        print "OnButton_btn_open_other()"
#!XRCED:end-block:xrcframe_mainwindow.OnButton_btn_open_other        

#!XRCED:begin-block:xrcframe_mainwindow.OnButton_btn_new
    def OnButton_btn_new(self, evt):
        # Replace with event handler code
        print "OnButton_btn_new()"
#!XRCED:end-block:xrcframe_mainwindow.OnButton_btn_new        


class xrcframe_projectwindow(wx.Frame):
#!XRCED:begin-block:xrcframe_projectwindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_projectwindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_projectwindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.thermal_season = self.GetMenuBar().FindItemById(xrc.XRCID("thermal_season"))
        self.tb_main = xrc.XRCCTRL(self, "tb_main")
        self.html_introduction = xrc.XRCCTRL(self, "html_introduction")
        self.pnl_errors = xrc.XRCCTRL(self, "pnl_errors")
        self.list_errors = xrc.XRCCTRL(self, "list_errors")
        self.btn_errors = xrc.XRCCTRL(self, "btn_errors")
        self.prg_progress = xrc.XRCCTRL(self, "prg_progress")
        self.btn_run = xrc.XRCCTRL(self, "btn_run")

        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_NEW, id=wx.ID_NEW)
        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_OPEN, id=wx.ID_OPEN)
        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_SAVE, id=wx.ID_SAVE)
        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_SAVEAS, id=wx.ID_SAVEAS)
        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_CLOSE, id=wx.ID_CLOSE)
        self.Bind(wx.EVT_MENU, self.OnMenu_wxID_EXIT, id=wx.ID_EXIT)
        self.Bind(wx.EVT_MENU, self.OnMenu_create_preset, id=xrc.XRCID('create_preset'))
        self.Bind(wx.EVT_MENU, self.OnMenu_manage_presets, id=xrc.XRCID('manage_presets'))
        self.Bind(wx.EVT_MENU, self.OnMenu_thermal_season, self.thermal_season)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_errors, self.btn_errors)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_run, self.btn_run)
        self.Bind(wx.EVT_CLOSE, self.OnClose)

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_NEW
    def OnMenu_wxID_NEW(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_NEW()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_NEW        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_OPEN
    def OnMenu_wxID_OPEN(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_OPEN()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_OPEN        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_SAVE
    def OnMenu_wxID_SAVE(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_SAVE()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_SAVE        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_SAVEAS
    def OnMenu_wxID_SAVEAS(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_SAVEAS()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_SAVEAS        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_CLOSE
    def OnMenu_wxID_CLOSE(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_CLOSE()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_CLOSE        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_wxID_EXIT
    def OnMenu_wxID_EXIT(self, evt):
        # Replace with event handler code
        print "OnMenu_wxID_EXIT()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_wxID_EXIT        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_create_preset
    def OnMenu_create_preset(self, evt):
        # Replace with event handler code
        print "OnMenu_create_preset()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_create_preset        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_manage_presets
    def OnMenu_manage_presets(self, evt):
        # Replace with event handler code
        print "OnMenu_manage_presets()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_manage_presets        

#!XRCED:begin-block:xrcframe_projectwindow.OnMenu_thermal_season
    def OnMenu_thermal_season(self, evt):
        # Replace with event handler code
        print "OnMenu_thermal_season()"
#!XRCED:end-block:xrcframe_projectwindow.OnMenu_thermal_season        

#!XRCED:begin-block:xrcframe_projectwindow.OnButton_btn_errors
    def OnButton_btn_errors(self, evt):
        # Replace with event handler code
        print "OnButton_btn_errors()"
#!XRCED:end-block:xrcframe_projectwindow.OnButton_btn_errors        

#!XRCED:begin-block:xrcframe_projectwindow.OnButton_btn_run
    def OnButton_btn_run(self, evt):
        # Replace with event handler code
        print "OnButton_btn_run()"
#!XRCED:end-block:xrcframe_projectwindow.OnButton_btn_run        

#!XRCED:begin-block:xrcframe_projectwindow.OnClose
    def OnClose(self, evt):
        # Replace with event handler code
        print "OnClose()"
#!XRCED:end-block:xrcframe_projectwindow.OnClose        


class xrcdialog_presets(wx.Dialog):
#!XRCED:begin-block:xrcdialog_presets.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcdialog_presets.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "dialog_presets")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.presetlist = xrc.XRCCTRL(self, "presetlist")
        self.paramlist_dummy = xrc.XRCCTRL(self, "paramlist_dummy")
        self.lbl_comment = xrc.XRCCTRL(self, "lbl_comment")
        self.wxID_DELETE = xrc.XRCCTRL(self, "wxID_DELETE")

        self.Bind(wx.EVT_BUTTON, self.OnButton_wxID_DELETE, self.wxID_DELETE)

#!XRCED:begin-block:xrcdialog_presets.OnButton_wxID_DELETE
    def OnButton_wxID_DELETE(self, evt):
        # Replace with event handler code
        print "OnButton_wxID_DELETE()"
#!XRCED:end-block:xrcdialog_presets.OnButton_wxID_DELETE        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ui_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="frame_mainwindow">
    <title>DO3SE</title>
    <object class="wxPanel">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxHtmlWindow" name="html_about">
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxStaticText">
                <label>Recent projects</label>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="sizeritem">
              <object class="wxListBox" name="list_recent">
                <content>
                  <item>C:\\DO3SE\\A project\\project.do3se</item>
                  <item>C:\\Users\\Alan\\My Documents\\Someplace\\someplace.do3se</item>
                  <item>R:\\something.do3se</item>
                </content>
                <style>wxLB_SINGLE</style>
                <XRCED>
                  <events>EVT_LISTBOX|EVT_LISTBOX_DCLICK</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxVERTICAL</orient>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>5</border>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxButton" name="btn_open_selected">
                <label>Open &amp;selected</label>
                <enabled>0</enabled>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_open_other">
                <label>&amp;Open other...</label>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_new">
                <label>&amp;New project</label>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>0</option>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxHORIZONTAL</orient>
          </object>
          <flag>wxBOTTOM|wxLEFT|wxRIGHT|wxALIGN_RIGHT</flag>
          <border>5</border>
        </object>
      </object>
    </object>
  </object>
  <object class="wxFrame" name="frame_projectwindow">
    <object class="wxMenuBar">
      <object class="wxMenu">
        <object class="wxMenuItem" name="wxID_NEW">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="wxID_OPEN">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="wxID_SAVE">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="wxID_SAVEAS">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="wxID_CLOSE">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="wxID_EXIT">
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <label>&amp;Project</label>
      </object>
      <object class="wxMenu">
        <label>&amp;Tools</label>
        <object class="wxMenuItem" name="create_preset">
          <label>&amp;Create preset</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="manage_presets">
          <label>Manage/&amp;apply presets</label>
          <XRCED>
            <events>EVT_MENU</events>
          </XRCED>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="thermal_season">
          <label>SGS/EGS from thermal time</label>
          <XRCED>
            <events>EVT_MENU</events>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
      </object>
    </object>
    <object class="wxPanel">
      <object class="wxBoxSizer">
        <orient>wxVERTICAL</orient>
        <object class="sizeritem">
          <object class="wxTreebook" name="tb_main">
            <object class="treebookpage">
              <object class="wxPanel">
                <object class="wxBoxSizer">
                  <orient>wxVERTICAL</orient>
                  <object class="sizeritem">
                    <object class="wxHtmlWindow" name="html_introduction">
                      <htmlcode>&lt;p&gt;
This is the main project window.  Each of the items on the left refer to a group of model parameters/settings which can be changed.
&lt;/p&gt;
&lt;p&gt;
To get help on a particular parameter, click the question mark in the bottom left corner of the window and then click the parameter input.  For further help, refer to the user manual.
&lt;/p&gt;</htmlcode>
                      <style>wxNO_BORDER</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                </object>
              </object>
              <label>Introduction</label>
              <depth>0</depth>
            </object>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <option>1</option>
          <flag>wxEXPAND</flag>
        </object>
        <object class="sizeritem">
          <object class="wxPanel" name="pnl_errors">
            <object class="wxBoxSizer">
              <orient>wxVERTICAL</orient>
              <object class="sizeritem">
                <object class="wxStaticText">
                  <label>Errors</label>
                </object>
              </object>
              <object class="sizeritem">
                <object class="wxListBox" name="list_errors">
                  <content>
                    <item>Somebody stole your cheese sandwich</item>
                    <item>Garden gnomes are riding your cat</item>
                  </content>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
            </object>
            <hidden>1</hidden>
            <XRCED>
              <assign_var>1</assign_var>
            </XRCED>
          </object>
          <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
          <border>5</border>
        </object>
        <object class="sizeritem">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxButton" name="btn_errors">
                <label>121 errors (click for more information)</label>
                <fg>#FF1111</fg>
                <style>wxNO_BORDER|wxNO_BORDER</style>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxGauge" name="prg_progress">
                <range>100</range>
                <value>0</value>
                <XRCED>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <option>1</option>
              <flag>wxEXPAND</flag>
            </object>
            <object class="spacer">
              <size>5</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="btn_run">
                <label>Run</label>
                <enabled>0</enabled>
                <XRCED>
                  <events>EVT_BUTTON</events>
                  <assign_var>1</assign_var>
                </XRCED>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <orient>wxHORIZONTAL</orient>
          </object>
          <flag>wxALL|wxEXPAND</flag>
          <border>5</border>
        </object>
      </object>
    </object>
    <title>DO3SE (foo.do3se)</title>
    <XRCED>
      <events>EVT_CLOSE</events>
    </XRCED>
  </object>
  <object class="wxDialog" name="dialog_presets">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxTreeCtrl" name="presetlist">
              <style>wxTR_HIDE_ROOT|wxTR_DEFAULT_STYLE</style>
              <XRCED>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5</size>
          </object>
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxPanel" name="paramlist_dummy">
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <option>1</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="sizeritem">
                <object class="wxStaticText" name="lbl_comment">
                  <label>(No description)</label>
                  <hidden>1</hidden>
                  <XRCED>
                    <assign_var>1</assign_var>
                  </XRCED>
                </object>
                <flag>wxTOP|wxBOTTOM|wxRIGHT|wxEXPAND</flag>
                <border>5</border>
              </object>
              <orient>wxVERTICAL</orient>
            </object>
            <option>2</option>
            <flag>wxEXPAND</flag>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxButton" name="wxID_DELETE">
              <enabled>0</enabled>
              <XRCED>
                <events>EVT_BUTTON</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxPanel"/>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="wxID_CANCEL"/>
            <flag>wxALIGN_RIGHT</flag>
          </object>
          <object class="spacer">
            <size>5</size>
          </object>
          <object class="sizeritem">
            <object class="wxButton" name="wxID_APPLY"/>
            <flag>wxALIGN_RIGHT</flag>
          </object>
          <orient>wxHORIZONTAL</orient>
        </object>
        <flag>wxALL|wxEXPAND|wxALIGN_RIGHT</flag>
        <border>5</border>
      </object>
    </object>
    <title>Apply preset</title>
    <style>wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ui/ui_xrc', ui_xrc)
    __res.Load('memory:XRC/ui/ui_xrc')

