# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcframe_mainwindow(wx.Frame):
#!XRCED:begin-block:xrcframe_mainwindow.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_mainwindow.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_mainwindow")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers



class xrcframe_project(wx.Frame):
#!XRCED:begin-block:xrcframe_project.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcframe_project.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "frame_project")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ui_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxFrame" name="frame_mainwindow">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxHtmlWindow">
          <size>500, 300</size>
        </object>
        <option>1</option>
        <flag>wxBOTTOM|wxEXPAND</flag>
        <border>5</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticText">
              <label>Recent projects</label>
            </object>
          </object>
          <object class="sizeritem">
            <object class="wxListBox" name="recent_projects">
              <style>wxLB_SINGLE</style>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <object class="sizeritem">
                <object class="wxButton" name="btn_open_recent">
                  <label>Open &amp;selected</label>
                </object>
                <option>0</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>5</size>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="btn_open_other">
                  <label>&amp;Open other...</label>
                </object>
                <option>0</option>
                <flag>wxEXPAND</flag>
              </object>
              <object class="spacer">
                <size>5</size>
              </object>
              <object class="sizeritem">
                <object class="wxButton" name="btn_new">
                  <label>&amp;New project</label>
                </object>
              </object>
              <orient>wxHORIZONTAL</orient>
            </object>
            <flag>wxTOP|wxALIGN_RIGHT</flag>
            <border>5</border>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <flag>wxEXPAND</flag>
      </object>
    </object>
    <size>600,400</size>
    <title>DO3SE</title>
  </object>
  <object class="wxFrame" name="frame_project">
    <object class="wxMenuBar">
      <object class="wxMenu">
        <object class="wxMenuItem">
          <label>New</label>
          <bitmap stock_id="wxART_NEW"/>
        </object>
        <object class="wxMenuItem">
          <label>Open...</label>
          <bitmap stock_id="wxART_FILE_OPEN"/>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem">
          <label>Save</label>
          <bitmap stock_id="wxART_FILE_SAVE"/>
        </object>
        <object class="wxMenuItem">
          <label>Save as...</label>
          <bitmap stock_id="wxART_FILE_SAVE_AS"/>
        </object>
        <object class="wxMenuItem">
          <label>Close</label>
          <bitmap stock_id="wxART_CROSS_MARK"/>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem">
          <label>Close all</label>
          <bitmap stock_id="wxART_QUIT"/>
        </object>
        <label>&amp;Project</label>
      </object>
      <object class="wxMenu">
        <label>&amp;Tools</label>
      </object>
    </object>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxTreebook">
          <object class="treebookpage">
            <object class="wxPanel">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxHtmlWindow">
                    <htmlcode>&lt;p&gt;
This is the main project window.  Each of the items on the left refer to a group of model parameters/settings which can be changed.
&lt;/p&gt;</htmlcode>
                    <style>wxNO_BORDER</style>
                  </object>
                  <option>1</option>
                  <flag>wxEXPAND</flag>
                </object>
              </object>
            </object>
            <label>Introduction</label>
            <depth>0</depth>
          </object>
          <style>wxBK_LEFT</style>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxStaticLine"/>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <object class="wxButton" name="btn_errors">
              <label>121 errors (click for more information)</label>
              <fg>#FF1111</fg>
              <style>wxNO_BORDER|wxNO_BORDER</style>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5</size>
          </object>
          <object class="sizeritem">
            <object class="wxGauge" name="prg_progress">
              <range>100</range>
              <value>50</value>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5</size>
          </object>
          <object class="sizeritem">
            <object class="wxButton">
              <label>Run</label>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>5</size>
          </object>
          <object class="sizeritem">
            <object class="wxButton">
              <label>Close</label>
            </object>
            <flag>wxEXPAND</flag>
          </object>
        </object>
        <flag>wxEXPAND</flag>
      </object>
    </object>
    <title>DO3SE (foo.do3se)</title>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ui/ui_xrc', ui_xrc)
    __res.Load('memory:XRC/ui/ui_xrc')

