name: Publish
on:
  push:
    branches:
      - RELEASE
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        working-directory: ./.github/scripts
        run: publish.sh
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.PRIVATE_RELEASE_REPO_SECRET }}"
