name: Publish
on:
  push:
    branches:
      - RELEASE
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r requirements/common.txt
          pip install -r requirements/deployment.txt
          pip install --upgrade build
        shell: bash
      - name: Build
        run: python -m Build
        shell: bash
      - name: Publish
        run: ./.github/scripts/publish.sh
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.PRIVATE_RELEASE_REPO_SECRET }}"
          GH_TOKEN: ${{ github.token }}
