name: Publish
on:
  push:
    branches:
      - RELEASE
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        run: ./.github/scripts/publish.sh
        env:
          GITHUB_TOKEN: "${{ secrets.PRIVATE_RELEASE_REPO_SECRET }}"
