name: Publish
on:
  push:
    branches:
      - RELEASE
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        run: ./.github/scripts/publish.sh
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.PRIVATE_RELEASE_REPO_SECRET }}"
          GH_TOKEN: ${{ github.token }}
